#!/usr/bin/env python3
import time
import pyautogui

time.sleep(5)

with open('/opt/songs.txt','r') as songfile:
	songlist = songfile.read().split('\n')
	for song in songlist:
		if song.startswith('-p'):
			pyautogui.typewrite(song)
			pyautogui.press('Enter')
			time.sleep(1.2)