#!/usr/bin/env python3 
from selenium import webdriver
from base64 import b64decode

browser = webdriver.Chrome()
browser.maximize_window()

browser.get('https://mobile-tracker-free.com/login/')

un = b64decode('YXF1aWJqYXZlZHQwMDdAZ21haWwuY29t')
pw = b64decode('YkNoSnJTU3RAMDA3')

browser.find_element_by_xpath('//*[@id="email"]').send_keys(str(un)[2:-1])
browser.find_element_by_xpath('//*[@id="password"]').send_keys(str(pw)[2:-1])
browser.find_element_by_xpath('//*[@id="btnLogin"]').click()